default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: car_app_development

test:
  <<: *default
  database: car_app_test

production:
  <<: *default
  database: car_app_production
  username: car_app
  password: <%= ENV["CAR_APP_DATABASE_PASSWORD"] %>
